(function(){
  function wait(){if(typeof openPanel!=='function'||typeof openModal!=='function'||!document.querySelector('.admin-nav'))return setTimeout(wait,60);install();waitData();}
  function install(){if(document.getElementById('aboutAdmin'))return;const nav=document.querySelector('.admin-nav');const before=nav.querySelector('[data-panel="newsAdmin"]')||nav.querySelector('[data-panel="tv"]')||nav.querySelector('[data-panel="contacts"]');const b=document.createElement('button');b.className='nav-btn';b.dataset.panel='aboutAdmin';b.textContent='ℹ️ Chi siamo';b.onclick=()=>openPanel('aboutAdmin');nav.insertBefore(b,before);
    const main=document.querySelector('.admin-layout main'),sticky=main.querySelector('.sticky-save');const s=document.createElement('section');s.className='admin-panel';s.id='aboutAdmin';s.innerHTML=`<div class="panel-head"><div><h2>Chi siamo</h2><p>Modifica i contenuti della pagina Chi siamo del sito.</p></div></div><div class="fields"><div class="field full"><label>Titolo principale</label><input id="abTitle"></div><div class="field full"><label>Introduzione</label><textarea id="abIntro"></textarea></div><div class="field full"><label>Presentazione della società</label><textarea id="abPresentation"></textarea></div><div class="field full"><label>Missione</label><textarea id="abMission"></textarea></div><div class="field full"><label>Valori</label><textarea id="abValues"></textarea></div><div class="field full"><label>Discipline</label><textarea id="abDisciplines"></textarea></div><div class="field full"><label>Territorio e storia</label><textarea id="abTerritory"></textarea></div><div class="field full"><label>Immagine principale</label><input id="abImage" placeholder="URL immagine"><input id="abImageFile" type="file" accept="image/jpeg,image/png,image/webp"><small>Puoi caricare o sostituire l'immagine della pagina.</small></div><div class="field"><label>Testo pulsante Staff</label><input id="abStaffLabel"></div><div class="field"><label>Link pulsante Staff</label><input id="abStaffUrl"></div><div class="field"><label>Testo pulsante Contatti</label><input id="abContactLabel"></div><div class="field"><label>Link pulsante Contatti</label><input id="abContactUrl"></div></div><div class="toolbar"><button class="btn btn-dark" id="abApply">Applica modifiche</button></div><p class="upload-note">Dopo aver applicato le modifiche premi “Salva online” in basso.</p>`;main.insertBefore(s,sticky);document.getElementById('abApply').onclick=apply;
    const dash=document.querySelector('#dashboard .item-list');if(dash){dash.insertAdjacentHTML('beforeend','<div class="item-card"><div><h3>ℹ️ Chi siamo</h3><p>Modifica presentazione, missione, valori, storia e immagine.</p></div><button class="btn btn-dark btn-small" id="jumpAboutAdmin">Apri</button></div>');document.getElementById('jumpAboutAdmin').onclick=()=>openPanel('aboutAdmin');}}
  function ensure(){data.about=data.about||{title:'CHI SIAMO',intro:'Una società, una comunità, una famiglia giallonera.',presentation:'ASD SGM Spadafora Sport è una realtà multisport che unisce attività agonistica, settore giovanile e presenza sul territorio.',mission:'Crescere attraverso lo sport, valorizzando persone, responsabilità e appartenenza.',values:'Passione, rispetto, comunità, crescita e spirito di squadra.',disciplines:'Calcio a 5, pallavolo, basket e attività giovanili.',territory:'Un progetto sportivo legato a Spadafora e alla sua comunità.',image:'',staff_button_label:'Scopri lo staff',staff_button_url:'staff.html',contact_button_label:'Contattaci',contact_button_url:'contatti.html'};return data.about;}
  function fill(){const a=ensure();const v=(id,x)=>{const e=document.getElementById(id);if(e)e.value=x||''};v('abTitle',a.title);v('abIntro',a.intro);v('abPresentation',a.presentation);v('abMission',a.mission);v('abValues',a.values);v('abDisciplines',a.disciplines);v('abTerritory',a.territory);v('abImage',a.image);v('abStaffLabel',a.staff_button_label);v('abStaffUrl',a.staff_button_url);v('abContactLabel',a.contact_button_label);v('abContactUrl',a.contact_button_url);}
  async function apply(){const a=ensure();a.title=document.getElementById('abTitle').value.trim();a.intro=document.getElementById('abIntro').value.trim();a.presentation=document.getElementById('abPresentation').value.trim();a.mission=document.getElementById('abMission').value.trim();a.values=document.getElementById('abValues').value.trim();a.disciplines=document.getElementById('abDisciplines').value.trim();a.territory=document.getElementById('abTerritory').value.trim();a.image=document.getElementById('abImage').value.trim();a.staff_button_label=document.getElementById('abStaffLabel').value.trim();a.staff_button_url=document.getElementById('abStaffUrl').value.trim();a.contact_button_label=document.getElementById('abContactLabel').value.trim();a.contact_button_url=document.getElementById('abContactUrl').value.trim();const f=document.getElementById('abImageFile').files[0];try{if(f){a.image=await window.SGM_DB.uploadImage(f,'chi-siamo');document.getElementById('abImage').value=a.image;}if(typeof status==='function')status('Chi siamo aggiornato nell’editor. Premi “Salva online” per pubblicare.');}catch(e){alert('Errore caricamento immagine: '+e.message)}}
  function waitData(){if(typeof data==='undefined'||!data)return setTimeout(waitData,100);ensure();fill();}
  wait();
})();