(function(){
  function wait(){if(typeof openPanel!=='function'||!document.querySelector('.admin-nav'))return setTimeout(wait,60);install();waitData();}
  function install(){if(document.getElementById('aboutAdmin'))return;const nav=document.querySelector('.admin-nav');const before=nav.querySelector('[data-panel="contacts"]')||null;const b=document.createElement('button');b.className='nav-btn';b.dataset.panel='aboutAdmin';b.textContent='ℹ️ Chi siamo';b.onclick=()=>openPanel('aboutAdmin');nav.insertBefore(b,before);
    const main=document.querySelector('.admin-layout main'),sticky=main.querySelector('.sticky-save');const s=document.createElement('section');s.className='admin-panel';s.id='aboutAdmin';s.innerHTML=`<div class="panel-head"><div><h2>Chi siamo</h2><p>Modifica i contenuti principali della pagina Chi siamo.</p></div></div><div class="fields"><div class="field full"><label>Titolo principale</label><input id="abTitle"></div><div class="field full"><label>Introduzione</label><textarea id="abIntro"></textarea></div><div class="field full"><label>Presentazione della società</label><textarea id="abPresentation" style="min-height:220px"></textarea></div><div class="field full"><label>Immagine principale</label><input id="abImage" placeholder="URL immagine"><input id="abImageFile" type="file" accept="image/jpeg,image/png,image/webp"><small>Puoi caricare o sostituire l'immagine della pagina.</small></div><div class="field"><label>Testo pulsante Staff</label><input id="abStaffLabel"></div><div class="field"><label>Link pulsante Staff</label><input id="abStaffUrl"></div><div class="field"><label>Testo pulsante Contatti</label><input id="abContactLabel"></div><div class="field"><label>Link pulsante Contatti</label><input id="abContactUrl"></div></div><div class="toolbar"><button class="btn btn-dark" id="abApply">Applica modifiche</button></div><p class="upload-note">Dopo aver applicato le modifiche premi “Salva online” in basso.</p>`;main.insertBefore(s,sticky);document.getElementById('abApply').onclick=apply;
    const dash=document.querySelector('#dashboard .item-list');if(dash){dash.insertAdjacentHTML('beforeend','<div class="item-card"><div><h3>ℹ️ Chi siamo</h3><p>Modifica titolo, introduzione, presentazione e immagine.</p></div><button class="btn btn-dark btn-small" id="jumpAboutAdmin">Apri</button></div>');document.getElementById('jumpAboutAdmin').onclick=()=>openPanel('aboutAdmin');}}
  function ensure(){data.about=data.about||{};const a=data.about;if(!a.title)a.title='CHI SIAMO';if(!a.intro)a.intro='Una società, una comunità, una famiglia giallonera.';if(!a.presentation)a.presentation='ASD SGM Spadafora Sport è una realtà multisport che unisce attività agonistica, settore giovanile e presenza sul territorio.';if(!a.staff_button_label)a.staff_button_label='Scopri lo staff';if(!a.staff_button_url)a.staff_button_url='staff.html';if(!a.contact_button_label)a.contact_button_label='Contattaci';if(!a.contact_button_url)a.contact_button_url='contatti.html';return a;}
  function fill(){const a=ensure();const v=(id,x)=>{const e=document.getElementById(id);if(e)e.value=x||''};v('abTitle',a.title);v('abIntro',a.intro);v('abPresentation',a.presentation);v('abImage',a.image);v('abStaffLabel',a.staff_button_label);v('abStaffUrl',a.staff_button_url);v('abContactLabel',a.contact_button_label);v('abContactUrl',a.contact_button_url);}
  async function apply(){const a=ensure();a.title=document.getElementById('abTitle').value.trim();a.intro=document.getElementById('abIntro').value.trim();a.presentation=document.getElementById('abPresentation').value.trim();a.image=document.getElementById('abImage').value.trim();a.staff_button_label=document.getElementById('abStaffLabel').value.trim();a.staff_button_url=document.getElementById('abStaffUrl').value.trim();a.contact_button_label=document.getElementById('abContactLabel').value.trim();a.contact_button_url=document.getElementById('abContactUrl').value.trim();delete a.mission;delete a.values;delete a.disciplines;delete a.territory;const f=document.getElementById('abImageFile').files[0];try{if(f){a.image=await window.SGM_DB.uploadImage(f,'chi-siamo');document.getElementById('abImage').value=a.image;}if(typeof status==='function')status('Chi siamo aggiornato nell’editor. Premi “Salva online” per pubblicare.');}catch(e){alert('Errore caricamento immagine: '+e.message)}}
  function waitData(){if(typeof data==='undefined'||!data)return setTimeout(waitData,100);ensure();fill();}
  wait();
})();