(function(){
const fallback=[
{section:'Direttivo',label:'presidente',name:'Mons. Alessandro Lo Nardo',role:'Presidente',photo:''},{section:'Direttivo',label:'vicepresidente',name:'Simone Scibilia',role:'Vicepresidente',photo:''},{section:'Direttivo',label:'segretario',name:'Aldo Ciuna',role:'Segretario',photo:''},{section:'Direttivo',label:'tesoriere',name:'Maria Ialacqua',role:'Tesoriere',photo:''},{section:'Direttivo',label:'consigliere',name:'Luca Scibilia',role:'Consigliere e dirigente delegato calcio a 5',photo:''},{section:'Direttivo',label:'consigliere',name:'Carmelo Floridia',role:'Consigliere e dirigente delegato pallavolo',photo:''},{section:'Direttivo',label:'consigliere',name:'Adriano Piccione',role:'Consigliere e dirigente delegato basket',photo:''},{section:'Direttivo',label:'consigliere',name:'Domenico Cannuli',role:'Consigliere',photo:''},{section:'Ufficio economico-amministrativo',label:'amministrazione',name:'Andrea Scibilia',role:'Ufficio economico-amministrativo',photo:''},{section:'Social Media Manager',label:'comunicazione',name:'Alessandro Scibilia',role:'Social Media Manager',photo:''},{section:'Calcio a 5',label:'calcio a 5',name:'Andrea Giacobbo',role:'Allenatore calcio a 5',photo:''},{section:'Calcio a 5',label:'calcio a 5',name:'Antonio Romeo',role:'Allenatore dei portieri calcio a 5',photo:''},{section:'Calcio a 5',label:'calcio a 5',name:'Antonio Vitale',role:'Dirigente calcio a 5',photo:''},{section:'Calcio a 5',label:'calcio a 5',name:'Pippo Arcoraci',role:'Dirigente calcio a 5',photo:''},{section:'Pallavolo',label:'pallavolo',name:'Gabriele Marchetta',role:'Allenatore pallavolo maschile',photo:''},{section:'Pallavolo',label:'pallavolo',name:'Giuseppe Cangemi',role:'Dirigente pallavolo maschile',photo:''},{section:'Pallavolo',label:'pallavolo',name:'Andrea Sapienza',role:'Dirigente pallavolo maschile',photo:''},{section:'Pallavolo',label:'pallavolo',name:'Dario Alberti',role:'Allievo allenatore pallavolo',photo:''},{section:'Basket',label:'basket',name:'Antonio Barbera',role:'Allenatore basket',photo:''},{section:'Basket',label:'basket',name:'Giuliano Anastasi',role:'Assistente allenatore basket',photo:''}
];
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;').replace(/>/g,'&gt;');
const meta={Direttivo:['SOCIETÀ','Direttivo'],'Ufficio economico-amministrativo':['AMMINISTRAZIONE','Ufficio economico-amministrativo'],'Social Media Manager':['COMUNICAZIONE','Social Media Manager'],'Calcio a 5':['AREA SPORTIVA','Calcio a 5'],Pallavolo:['AREA SPORTIVA','Pallavolo'],Basket:['AREA SPORTIVA','Basket']};
function render(arr){const root=document.getElementById('staff-content');if(!root)return;const order=['Direttivo','Ufficio economico-amministrativo','Social Media Manager','Calcio a 5','Pallavolo','Basket'];root.innerHTML=order.map((sec,i)=>{const people=arr.filter(x=>x.section===sec);if(!people.length)return'';const m=meta[sec]||['STAFF',sec];return `<section class="staff-section ${i%2?'alt':''}"><div class="container"><div class="staff-section-head"><p class="section-kicker yellow">${m[0]}</p><h2>${m[1]}</h2></div><div class="staff-grid ${people.length===1?'single':''}">${people.map(p=>`<article class="staff-card"><div class="staff-photo ${p.photo?'has-photo':''}" ${p.photo?`style="background-image:url('${esc(p.photo)}')"`:''}>${p.photo?'':'<div class="placeholder">Foto non inserita</div>'}</div><div class="staff-card-body"><span>${esc(p.label||sec)}</span><h3>${esc(p.name)}</h3><p>${esc(p.role)}</p></div></article>`).join('')}</div></div></section>`}).join('');}
async function load(){try{if(!window.SGM_DB||!document.getElementById('staff-content'))return setTimeout(load,80);await window.SGM_DB.init();let arr=fallback;if(window.SGM_DB.enabled){const d=await window.SGM_DB.getSiteData();if(Array.isArray(d.general_staff)&&d.general_staff.length)arr=d.general_staff;else if(d.generalStaffPhotos){arr=fallback.map(p=>({...p,photo:d.generalStaffPhotos[String(p.name).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')]||''}));}}render(arr);}catch(e){console.warn('Staff dinamico non disponibile',e);render(fallback);}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load);else load();
})();