import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, Image, Pressable, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { fetchSiteData, subscribeSiteData } from './src/lib/siteData';
import { registerForPushNotificationsAsync } from './src/lib/notifications';
import { C, Card, Hero, ScreenTitle } from './src/components/ui';
import type { Match, SitePayload, Sport } from './src/types/site';

const sportsOrder=['calcio_a_5','pallavolo_maschile','pallavolo_femminile','basket','settore_giovanile'];
const sportMeta:Record<string,{label:string;icon:string}>={
 calcio_a_5:{label:'Calcio a 5',icon:'soccer'},
 pallavolo_maschile:{label:'Pallavolo M',icon:'volleyball'},
 pallavolo_femminile:{label:'Pallavolo F',icon:'volleyball'},
 basket:{label:'Basket',icon:'basketball'},
 settore_giovanile:{label:'Giovanili',icon:'account-group-outline'},
};
type TabName='Home'|'Squadre'|'News'|'Risultati'|'Altro';
type TeamSection='Rosa'|'Calendario'|'Classifica'|'Staff';
const tabs:TabName[]=['Home','Squadre','News','Risultati','Altro'];

function useSite(){
 const [data,setData]=useState<SitePayload|null>(null); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState('');
 const load=useCallback(async(silent=false)=>{try{if(!silent)setError(''); const d=await fetchSiteData(); setData(d);}catch(e:any){setError(e?.message??'Errore di connessione');}finally{setLoading(false);setRefreshing(false);}},[]);
 useEffect(()=>{load(); const unsub=subscribeSiteData(()=>load(true)); return unsub;},[load]);
 return {data,loading,error,refreshing,refresh:()=>{setRefreshing(true);load(true);}};
}
function Loader(){return <View style={st.center}><ActivityIndicator size="large" color={C.yellow}/><Text style={st.muted}>Caricamento SGM…</Text></View>}
function Empty({text}:{text:string}){return <Card><Text style={st.muted}>{text}</Text></Card>}

function MatchCard({m,featured=false}:{m:Match;featured?:boolean}){
 return <View style={[st.matchCard,featured&&st.matchCardFeatured]}>
  <View style={st.matchTop}><Text style={st.matchSport}>{m.sport||'SGM'}</Text>{m.date||m.time?<Text style={st.matchDate}>{[m.date,m.time].filter(Boolean).join(' · ')}</Text>:null}</View>
  <View style={st.matchTeams}><Text style={st.matchTeam}>{m.home||'—'}</Text><View style={st.vsPill}><Text style={st.vsText}>VS</Text></View><Text style={[st.matchTeam,{textAlign:'right'}]}>{m.away||'—'}</Text></View>
 </View>
}
function ResultCard({m}:{m:Match}){
 return <View style={st.resultCard}><Text style={st.resultSport}>{m.sport||'SGM'}</Text><View style={st.resultRow}><Text style={st.resultTeam}>{m.home||'—'}</Text><Text style={st.resultScore}>{m.home_score??'-'} : {m.away_score??'-'}</Text><Text style={[st.resultTeam,{textAlign:'right'}]}>{m.away||'—'}</Text></View><Text style={st.resultDate}>{m.date||''}</Text></View>
}

function Home({onOpenSport}:{onOpenSport:(key:string)=>void}){
 const x=useSite(); if(x.loading&&!x.data)return <Loader/>; const d=x.data??{}; const next=d.next_matches??[]; const results=d.recent_results??[]; const sports=d.sports??{};
 return <ScrollView style={st.page} contentContainerStyle={st.scrollContent} refreshControl={<RefreshControl refreshing={x.refreshing} onRefresh={x.refresh} tintColor={C.yellow}/>}>
  <Hero {...d.home_hero} season={d.season}/>
  <View style={st.homeSection}><Text style={st.homeKicker}>LE NOSTRE DISCIPLINE</Text><Text style={st.homeHeading}>Tutta SGM in un tocco</Text></View>
  <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={st.sportQuickRow}>
   {sportsOrder.map(k=>{const s=sports[k]; if(!s)return null; const meta=sportMeta[k]; return <Pressable key={k} onPress={()=>onOpenSport(k)} style={({pressed})=>[st.sportQuick,pressed&&st.pressed]}><View style={st.sportIconCircle}><MaterialCommunityIcons name={(meta?.icon||'trophy-outline') as any} size={25} color={C.yellow}/></View><Text style={st.sportQuickName}>{s.name||meta?.label||k}</Text><Text style={st.sportQuickLeague} numberOfLines={1}>{s.league_name||'Stagione 2026/27'}</Text><MaterialCommunityIcons name="chevron-right" size={20} color={C.yellow}/></Pressable>})}
  </ScrollView>
  <ScreenTitle kicker="IN EVIDENZA" title="Prossima gara"/>
  {next.length?<><View style={{marginHorizontal:18}}><MatchCard m={next[0]} featured/></View>{next.length>1?<View style={st.moreMatches}>{next.slice(1,3).map((m,i)=><MatchCard key={i} m={m}/>)}</View>:null}</>:<Empty text="Nessuna gara programmata."/>}
  <ScreenTitle kicker="DAL CAMPO" title="Ultimi risultati"/>
  {results.length?<View style={st.resultsGrid}>{results.slice(0,3).map((m,i)=><ResultCard key={i} m={m}/>)}</View>:<Empty text="Nessun risultato disponibile."/>}
  <ScreenTitle kicker="ULTIMI AGGIORNAMENTI" title="News"/>
  {(d.news??[]).slice(0,3).map((n,i)=><Card key={i}>{n.image?<Image source={{uri:n.image}} style={st.newsImg}/>:null}<Text style={st.newsTitle}>{n.title}</Text><Text style={st.muted}>{n.date}</Text><Text style={st.body} numberOfLines={3}>{n.excerpt}</Text></Card>)}
 </ScrollView>
}

function Squadre({selectedKey,onSelectSport,onBack}:{selectedKey:string|null;onSelectSport:(key:string)=>void;onBack:()=>void}){
 const x=useSite(); if(x.loading&&!x.data)return <Loader/>; const sports=x.data?.sports??{};
 if(selectedKey&&sports[selectedKey])return <TeamDetail sportKey={selectedKey} sport={sports[selectedKey]} onBack={onBack} refreshing={x.refreshing} onRefresh={x.refresh}/>;
 return <ScrollView style={st.page} contentContainerStyle={st.scrollContent} refreshControl={<RefreshControl refreshing={x.refreshing} onRefresh={x.refresh} tintColor={C.yellow}/>}>
  <ScreenTitle kicker="ASD SGM SPADAFORA SPORT" title="Le squadre" subtitle="Scegli una disciplina per aprire rosa, calendario, classifica e staff."/>
  <View style={st.teamGrid}>{sportsOrder.map(k=>{const s=sports[k]; if(!s)return null; const meta=sportMeta[k]; return <Pressable key={k} onPress={()=>onSelectSport(k)} style={({pressed})=>[st.teamTile,pressed&&st.pressed]}><View style={st.teamTileTop}><View style={st.teamIcon}><MaterialCommunityIcons name={(meta?.icon||'trophy-outline') as any} size={30} color={C.yellow}/></View><MaterialCommunityIcons name="arrow-top-right" size={21} color={C.gray}/></View><Text style={st.teamTileName}>{s.name||meta?.label}</Text><Text style={st.teamTileLeague}>{s.league_name||'Stagione 2026/27'}</Text><View style={st.teamStats}><Text style={st.teamStat}><Text style={st.teamStatStrong}>{s.roster?.length??0}</Text> atleti</Text><Text style={st.teamStat}><Text style={st.teamStatStrong}>{s.staff?.length??0}</Text> staff</Text></View></Pressable>})}</View>
 </ScrollView>
}

function TeamDetail({sportKey,sport,onBack,refreshing,onRefresh}:{sportKey:string;sport:Sport;onBack:()=>void;refreshing:boolean;onRefresh:()=>void}){
 const [section,setSection]=useState<TeamSection>('Rosa'); const meta=sportMeta[sportKey]; const sections:TeamSection[]=['Rosa','Calendario','Classifica','Staff'];
 return <ScrollView style={st.page} contentContainerStyle={st.scrollContent} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor={C.yellow}/>}>
  <View style={st.teamHero}>
   <Pressable onPress={onBack} style={st.backButton}><MaterialCommunityIcons name="arrow-left" size={22} color={C.white}/><Text style={st.backText}>Squadre</Text></Pressable>
   <View style={st.teamHeroIcon}><MaterialCommunityIcons name={(meta?.icon||'trophy-outline') as any} size={42} color={C.yellow}/></View>
   <Text style={st.teamHeroKicker}>STAGIONE SPORTIVA 2026/2027</Text><Text style={st.teamHeroTitle}>{sport.name||meta?.label||'SGM'}</Text><Text style={st.teamHeroLeague}>{sport.league_name||'ASD SGM Spadafora Sport'}</Text>
  </View>
  <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={st.segmentRow}>{sections.map(s=><Pressable key={s} onPress={()=>setSection(s)} style={[st.segment,section===s&&st.segmentActive]}><Text style={[st.segmentText,section===s&&st.segmentTextActive]}>{s}</Text></Pressable>)}</ScrollView>
  {section==='Rosa'?<Roster sport={sport}/>:null}{section==='Calendario'?<Calendar sport={sport}/>:null}{section==='Classifica'?<Standings sport={sport}/>:null}{section==='Staff'?<Staff sport={sport}/>:null}
 </ScrollView>
}
function Roster({sport}:{sport:Sport}){return <View><ScreenTitle kicker="PRIMA SQUADRA" title="Rosa"/>{sport.roster?.length?<View style={st.rosterGrid}>{sport.roster.map((p,i)=><View key={i} style={st.playerCard}>{p.image?<Image source={{uri:p.image}} style={st.playerImage}/>:<View style={st.playerPlaceholder}><MaterialCommunityIcons name="account" size={45} color="#555"/></View>}<View style={st.playerInfo}><Text style={st.playerNumber}>{p.number??'—'}</Text><View style={{flex:1}}><Text style={st.playerName} numberOfLines={1}>{p.name}</Text><Text style={st.playerRole}>{p.role||'Atleta'}</Text></View></View></View>)}</View>:<Empty text="Rosa in aggiornamento."/>}</View>}
function Calendar({sport}:{sport:Sport}){return <View><ScreenTitle kicker="STAGIONE" title="Calendario"/>{sport.calendar?.length?sport.calendar.map((m,i)=><View key={i} style={{marginHorizontal:18,marginBottom:10}}><MatchCard m={m}/></View>):<Empty text="Calendario in aggiornamento."/>}</View>}
function Standings({sport}:{sport:Sport}){return <View><ScreenTitle kicker="CAMPIONATO" title="Classifica"/>{sport.standings?.length?<View style={st.standingsCard}><View style={st.tableHeader}><Text style={st.tableHeadPos}>#</Text><Text style={st.tableHeadTeam}>Squadra</Text><Text style={st.tableHead}>G</Text><Text style={st.tableHead}>Pt</Text></View>{sport.standings.map((r,i)=><View key={i} style={[st.tableRow,(r.team||'').toLowerCase().includes('sgm')&&st.tableRowSgm]}><Text style={st.pos}>{r.pos||i+1}</Text><Text style={st.tableTeam} numberOfLines={1}>{r.team}</Text><Text style={st.tablePlayed}>{r.played??'-'}</Text><Text style={st.pts}>{r.points??0}</Text></View>)}</View>:<Empty text="Classifica non ancora disponibile."/>}</View>}
function Staff({sport}:{sport:Sport}){return <View><ScreenTitle kicker="AREA TECNICA" title="Staff"/>{sport.staff?.length?<View style={st.staffGrid}>{sport.staff.map((p,i)=><View key={i} style={st.staffCard}>{p.image?<Image source={{uri:p.image}} style={st.staffImage}/>:<View style={st.staffPlaceholder}><MaterialCommunityIcons name="account-tie" size={38} color={C.yellow}/></View>}<Text style={st.staffName}>{p.name}</Text><Text style={st.staffRole}>{p.role||'Staff'}</Text></View>)}</View>:<Empty text="Staff in aggiornamento."/>}</View>}

function News(){const x=useSite(); if(x.loading&&!x.data)return <Loader/>; const news=x.data?.news??[]; return <FlatList style={st.page} contentContainerStyle={st.scrollContent} data={news} keyExtractor={(_,i)=>String(i)} refreshControl={<RefreshControl refreshing={x.refreshing} onRefresh={x.refresh} tintColor={C.yellow}/>} ListHeaderComponent={<ScreenTitle kicker="MONDO SGM" title="News"/>} ListEmptyComponent={<Empty text="Nessuna news pubblicata."/>} renderItem={({item:n})=><Card>{n.image?<Image source={{uri:n.image}} style={st.newsImg}/>:null}<Text style={st.newsTitle}>{n.title}</Text><Text style={st.muted}>{n.date}</Text><Text style={st.body}>{n.body??n.excerpt}</Text></Card>}/>}
function Risultati(){const x=useSite(); if(x.loading&&!x.data)return <Loader/>; const d=x.data??{}; return <ScrollView style={st.page} contentContainerStyle={st.scrollContent} refreshControl={<RefreshControl refreshing={x.refreshing} onRefresh={x.refresh} tintColor={C.yellow}/>}><ScreenTitle kicker="STAGIONE SPORTIVA" title="Risultati e classifiche"/><ScreenTitle title="Ultimi risultati"/>{(d.recent_results??[]).length?<View style={st.resultsGrid}>{(d.recent_results??[]).map((m,i)=><ResultCard key={i} m={m}/>)}</View>:<Empty text="Nessun risultato disponibile."/>}<ScreenTitle title="Classifiche"/>{sportsOrder.map(k=>{const s=d.sports?.[k]; if(!s?.standings?.length)return null; return <View key={k} style={st.standingsCardOuter}><Text style={st.standingSport}>{s.name}</Text><Text style={st.standingLeague}>{s.league_name}</Text>{s.standings.slice(0,8).map((r,i)=><View key={i} style={[st.tableRow,(r.team||'').toLowerCase().includes('sgm')&&st.tableRowSgm]}><Text style={st.pos}>{r.pos||i+1}</Text><Text style={st.tableTeam}>{r.team}</Text><Text style={st.pts}>{r.points??0} pt</Text></View>)}</View>})}</ScrollView>}
function Altro(){const x=useSite(); if(x.loading&&!x.data)return <Loader/>; const d=x.data??{}; return <ScrollView style={st.page} contentContainerStyle={st.scrollContent} refreshControl={<RefreshControl refreshing={x.refreshing} onRefresh={x.refresh} tintColor={C.yellow}/>}><ScreenTitle kicker="ASD SGM" title="Altro"/><Card><Text style={st.sportTitle}>Palmarès</Text><Text style={st.muted}>{Array.isArray(d.palmares)?`${d.palmares.length} elementi disponibili`:'Sezione disponibile dal sito'}</Text></Card><Card><Text style={st.sportTitle}>SGM TV</Text><Text style={st.muted}>{Array.isArray(d.sgm_tv)?`${d.sgm_tv.length} contenuti disponibili`:'Sezione disponibile dal sito'}</Text></Card><Card><Text style={st.sportTitle}>Sponsor</Text><Text style={st.muted}>{Array.isArray(d.sponsors)?`${d.sponsors.length} sponsor/contenuti disponibili`:'Sezione disponibile dal sito'}</Text></Card><Card><Text style={st.sportTitle}>Sincronizzazione</Text><Text style={st.body}>L’app legge lo stesso record Supabase usato dal sito. Quando salvi dal pannello amministratore, i nuovi dati vengono riletti automaticamente anche qui.</Text></Card></ScrollView>}

const tabIcons:Record<TabName,string>={Home:'home-variant',Squadre:'account-group',News:'newspaper-variant-outline',Risultati:'trophy-outline',Altro:'view-grid-outline'};
function NavIcon({tab,active}:{tab:TabName,active:boolean}){return <MaterialCommunityIcons name={tabIcons[tab] as any} size={27} color={active?C.yellow:'#8d8d8d'}/>}

export default function App(){
 const [active,setActive]=useState<TabName>('Home'); const [selectedSport,setSelectedSport]=useState<string|null>(null);
 useEffect(()=>{registerForPushNotificationsAsync().catch(()=>null);},[]);
 const openSport=(key:string)=>{setSelectedSport(key);setActive('Squadre');};
 const selectTab=(tab:TabName)=>{setActive(tab);if(tab!=='Squadre')setSelectedSport(null);};
 let screen:React.ReactNode=<Home onOpenSport={openSport}/>; if(active==='Squadre')screen=<Squadre selectedKey={selectedSport} onSelectSport={setSelectedSport} onBack={()=>setSelectedSport(null)}/>; else if(active==='News')screen=<News/>; else if(active==='Risultati')screen=<Risultati/>; else if(active==='Altro')screen=<Altro/>;
 return <SafeAreaView style={st.app}><StatusBar style="light"/><View style={st.header}><View><Text style={st.headerEyebrow}>ASD</Text><Text style={st.headerTitle}>SGM SPADAFORA SPORT</Text></View><View style={st.liveDot}/></View><View style={st.content}>{screen}</View><View style={st.tabBar}>{tabs.map(tab=>{const selected=active===tab;return <Pressable key={tab} accessibilityRole="button" accessibilityLabel={tab} onPress={()=>selectTab(tab)} android_ripple={{color:'#242424',borderless:false}} style={({pressed})=>[st.tabButton,selected&&st.tabButtonActive,pressed&&st.pressed]}><NavIcon tab={tab} active={selected}/><Text numberOfLines={1} style={[st.tabLabel,selected&&st.tabTextActive]}>{tab}</Text></Pressable>})}</View></SafeAreaView>
}

const st=StyleSheet.create({
 app:{flex:1,backgroundColor:C.black},header:{height:58,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:18,borderBottomWidth:1,borderBottomColor:C.border,backgroundColor:C.black},headerEyebrow:{color:C.yellow,fontWeight:'900',fontSize:8,letterSpacing:2},headerTitle:{color:C.white,fontWeight:'900',fontSize:15,letterSpacing:.45},liveDot:{width:9,height:9,borderRadius:9,backgroundColor:C.yellow},content:{flex:1,backgroundColor:C.black},page:{flex:1,backgroundColor:C.black},scrollContent:{paddingBottom:22},center:{flex:1,backgroundColor:C.black,alignItems:'center',justifyContent:'center',gap:12},muted:{color:C.gray,fontSize:13,lineHeight:18},yellow:{color:C.yellow,fontSize:12,fontWeight:'900',letterSpacing:.5},body:{color:C.white,fontSize:14,lineHeight:21,marginTop:8},sportTitle:{color:C.white,fontSize:23,fontWeight:'900',marginBottom:5},pressed:{opacity:.7},
 homeSection:{paddingHorizontal:18,paddingTop:22,paddingBottom:12},homeKicker:{color:C.yellow,fontSize:10,fontWeight:'900',letterSpacing:1.5},homeHeading:{color:C.white,fontSize:26,fontWeight:'900',marginTop:4},sportQuickRow:{paddingHorizontal:18,paddingBottom:4,gap:10},sportQuick:{width:150,minHeight:150,borderRadius:20,borderWidth:1,borderColor:C.border,backgroundColor:C.black2,padding:14,justifyContent:'space-between'},sportIconCircle:{width:45,height:45,borderRadius:15,alignItems:'center',justifyContent:'center',backgroundColor:'#24200b'},sportQuickName:{color:C.white,fontSize:16,fontWeight:'900',marginTop:12},sportQuickLeague:{color:C.gray,fontSize:11,marginTop:3,maxWidth:118},
 matchCard:{backgroundColor:C.black2,borderWidth:1,borderColor:C.border,borderRadius:18,padding:15},matchCardFeatured:{borderColor:'#665500',padding:19,backgroundColor:'#17150b'},matchTop:{flexDirection:'row',justifyContent:'space-between',gap:8},matchSport:{color:C.yellow,fontSize:10,fontWeight:'900',textTransform:'uppercase',letterSpacing:1},matchDate:{color:C.gray,fontSize:10,fontWeight:'700'},matchTeams:{flexDirection:'row',alignItems:'center',marginTop:18,gap:10},matchTeam:{flex:1,color:C.white,fontSize:16,fontWeight:'900'},vsPill:{width:36,height:28,borderRadius:9,backgroundColor:C.yellow,alignItems:'center',justifyContent:'center'},vsText:{color:C.black,fontSize:11,fontWeight:'900'},moreMatches:{paddingHorizontal:18,marginTop:10,gap:10},resultsGrid:{paddingHorizontal:18,gap:10},resultCard:{backgroundColor:C.black2,borderRadius:17,borderWidth:1,borderColor:C.border,padding:14},resultSport:{color:C.yellow,fontSize:10,fontWeight:'900',letterSpacing:1,textTransform:'uppercase'},resultRow:{flexDirection:'row',alignItems:'center',marginTop:10},resultTeam:{flex:1,color:C.white,fontWeight:'800',fontSize:12},resultScore:{color:C.yellow,fontSize:20,fontWeight:'900',paddingHorizontal:8},resultDate:{color:C.gray,fontSize:10,marginTop:8,textAlign:'center'},
 newsImg:{width:'100%',height:190,borderRadius:12,marginBottom:12,backgroundColor:C.border},newsTitle:{color:C.white,fontSize:20,fontWeight:'900',marginBottom:4},teamGrid:{paddingHorizontal:18,gap:12},teamTile:{borderRadius:21,borderWidth:1,borderColor:C.border,backgroundColor:C.black2,padding:17},teamTileTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},teamIcon:{width:54,height:54,borderRadius:17,backgroundColor:'#24200b',alignItems:'center',justifyContent:'center'},teamTileName:{color:C.white,fontSize:24,fontWeight:'900',marginTop:18},teamTileLeague:{color:C.yellow,fontSize:12,fontWeight:'800',marginTop:4},teamStats:{flexDirection:'row',gap:18,marginTop:18,paddingTop:12,borderTopWidth:1,borderTopColor:C.border},teamStat:{color:C.gray,fontSize:11},teamStatStrong:{color:C.white,fontWeight:'900'},
 teamHero:{padding:20,paddingBottom:24,backgroundColor:'#11100b',borderBottomWidth:1,borderBottomColor:'#403800'},backButton:{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:6,paddingVertical:8,paddingRight:12},backText:{color:C.white,fontWeight:'800'},teamHeroIcon:{width:70,height:70,borderRadius:22,backgroundColor:'#24200b',alignItems:'center',justifyContent:'center',marginTop:16},teamHeroKicker:{color:C.yellow,fontSize:10,fontWeight:'900',letterSpacing:1.4,marginTop:18},teamHeroTitle:{color:C.white,fontSize:34,fontWeight:'900',marginTop:4},teamHeroLeague:{color:C.gray,fontSize:13,fontWeight:'700',marginTop:5},segmentRow:{paddingHorizontal:18,paddingVertical:16,gap:8},segment:{paddingHorizontal:15,paddingVertical:10,borderRadius:12,borderWidth:1,borderColor:C.border,backgroundColor:C.black2},segmentActive:{backgroundColor:C.yellow,borderColor:C.yellow},segmentText:{color:C.gray,fontWeight:'900',fontSize:11},segmentTextActive:{color:C.black},
 rosterGrid:{paddingHorizontal:18,gap:10},playerCard:{overflow:'hidden',borderRadius:18,backgroundColor:C.black2,borderWidth:1,borderColor:C.border},playerImage:{width:'100%',height:220,backgroundColor:'#222'},playerPlaceholder:{height:130,alignItems:'center',justifyContent:'center',backgroundColor:'#171717'},playerInfo:{flexDirection:'row',alignItems:'center',padding:13},playerNumber:{width:42,color:C.yellow,fontSize:23,fontWeight:'900'},playerName:{color:C.white,fontSize:15,fontWeight:'900'},playerRole:{color:C.gray,fontSize:11,marginTop:2},standingsCard:{marginHorizontal:18,borderWidth:1,borderColor:C.border,borderRadius:18,overflow:'hidden',backgroundColor:C.black2},standingsCardOuter:{marginHorizontal:18,marginBottom:14,borderWidth:1,borderColor:C.border,borderRadius:18,overflow:'hidden',backgroundColor:C.black2,paddingTop:15},standingSport:{color:C.white,fontSize:19,fontWeight:'900',paddingHorizontal:14},standingLeague:{color:C.yellow,fontSize:11,fontWeight:'800',paddingHorizontal:14,marginTop:3,marginBottom:9},tableHeader:{flexDirection:'row',paddingHorizontal:12,paddingVertical:10,backgroundColor:'#1c1c1c'},tableHeadPos:{width:28,color:C.gray,fontSize:10,fontWeight:'900'},tableHeadTeam:{flex:1,color:C.gray,fontSize:10,fontWeight:'900'},tableHead:{width:36,textAlign:'center',color:C.gray,fontSize:10,fontWeight:'900'},tableRow:{flexDirection:'row',alignItems:'center',paddingHorizontal:12,paddingVertical:12,borderTopWidth:1,borderTopColor:C.border},tableRowSgm:{backgroundColor:'#211d08'},pos:{color:C.yellow,fontWeight:'900',width:28},tableTeam:{color:C.white,fontWeight:'700',flex:1},tablePlayed:{color:C.gray,width:36,textAlign:'center',fontWeight:'800'},pts:{color:C.white,fontWeight:'900',width:48,textAlign:'right'},staffGrid:{paddingHorizontal:18,gap:10},staffCard:{backgroundColor:C.black2,borderWidth:1,borderColor:C.border,borderRadius:18,padding:15,alignItems:'center'},staffImage:{width:92,height:92,borderRadius:46,backgroundColor:'#222',marginBottom:10},staffPlaceholder:{width:76,height:76,borderRadius:38,backgroundColor:'#24200b',alignItems:'center',justifyContent:'center',marginBottom:10},staffName:{color:C.white,fontSize:16,fontWeight:'900',textAlign:'center'},staffRole:{color:C.yellow,fontSize:11,fontWeight:'800',textAlign:'center',marginTop:3},
 tabBar:{height:76,flexDirection:'row',backgroundColor:'#080808',borderTopWidth:1,borderTopColor:'#242424',paddingBottom:4},tabButton:{flex:1,alignItems:'center',justifyContent:'center',minWidth:0,paddingTop:5},tabButtonActive:{borderTopWidth:3,borderTopColor:C.yellow,backgroundColor:'#101010'},tabLabel:{color:'#8d8d8d',fontSize:10,fontWeight:'800',marginTop:5},tabTextActive:{color:C.yellow}
});
