import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, FlatList, Image, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { StatusBar } from 'expo-status-bar';
import { fetchSiteData, subscribeSiteData } from './src/lib/siteData';
import { registerForPushNotificationsAsync } from './src/lib/notifications';
import { C, Card, Hero, ScreenTitle } from './src/components/ui';
import type { SitePayload, Sport } from './src/types/site';

const Tab=createBottomTabNavigator();
const sportsOrder=['calcio_a_5','pallavolo_maschile','pallavolo_femminile','basket','settore_giovanile'];
const icons:Record<string,string>={Home:'⌂',Squadre:'◆',News:'●',Risultati:'▣',Altro:'☰'};

function useSite(){
 const [data,setData]=useState<SitePayload|null>(null); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState('');
 const load=useCallback(async(silent=false)=>{try{if(!silent)setError(''); const d=await fetchSiteData(); setData(d);}catch(e:any){setError(e?.message??'Errore di connessione');}finally{setLoading(false);setRefreshing(false);}},[]);
 useEffect(()=>{load(); const unsub=subscribeSiteData(()=>load(true)); return unsub;},[load]);
 return {data,loading,error,refreshing,refresh:()=>{setRefreshing(true);load(true);}};
}

function Loader(){return <View style={st.center}><ActivityIndicator size="large" color={C.yellow}/><Text style={st.muted}>Caricamento SGM…</Text></View>}
function Empty({text}:{text:string}){return <Card><Text style={st.muted}>{text}</Text></Card>}

function Home(){const x=useSite(); if(x.loading&&!x.data)return <Loader/>; const d=x.data??{}; return <ScrollView style={st.page} refreshControl={<RefreshControl refreshing={x.refreshing} onRefresh={x.refresh} tintColor={C.yellow}/>}><Hero {...d.home_hero} season={d.season}/><ScreenTitle kicker="IN EVIDENZA" title="Prossime gare"/><>{(d.next_matches??[]).map((m,i)=><Card key={i}><Text style={st.yellow}>{m.sport}</Text><Text style={st.match}>{m.home}  —  {m.away}</Text><Text style={st.muted}>{m.date} · {m.time}</Text></Card>)}</><ScreenTitle kicker="ULTIMI AGGIORNAMENTI" title="News"/><>{(d.news??[]).slice(0,3).map((n,i)=><Card key={i}>{n.image?<Image source={{uri:n.image}} style={st.newsImg}/>:null}<Text style={st.newsTitle}>{n.title}</Text><Text style={st.muted}>{n.date}</Text><Text style={st.body}>{n.excerpt}</Text></Card>)}</></ScrollView>}

function Squadre(){const x=useSite(); if(x.loading&&!x.data)return <Loader/>; const sports=x.data?.sports??{}; return <ScrollView style={st.page} refreshControl={<RefreshControl refreshing={x.refreshing} onRefresh={x.refresh} tintColor={C.yellow}/>}><ScreenTitle kicker="ASD SGM SPADAFORA SPORT" title="Le squadre" subtitle="Rose e staff si aggiornano dallo stesso pannello amministratore del sito."/>{sportsOrder.map(k=>{const s=sports[k]; if(!s)return null; return <SportBlock key={k} sport={s}/>})}</ScrollView>}
function SportBlock({sport}:{sport:Sport}){return <Card><Text style={st.sportTitle}>{sport.name}</Text>{sport.league_name?<Text style={st.yellow}>{sport.league_name}</Text>:null}<Text style={st.sectionLabel}>ROSA</Text>{sport.roster?.length?(sport.roster.map((p,i)=><View key={i} style={st.row}><Text style={st.number}>{p.number??'–'}</Text><View><Text style={st.rowTitle}>{p.name}</Text><Text style={st.muted}>{p.role}</Text></View></View>)):<Text style={st.muted}>Rosa in aggiornamento</Text>}<Text style={st.sectionLabel}>STAFF</Text>{sport.staff?.map((p,i)=><View key={i} style={st.staffRow}><Text style={st.rowTitle}>{p.name}</Text><Text style={st.muted}>{p.role}</Text></View>)}</Card>}

function News(){const x=useSite(); if(x.loading&&!x.data)return <Loader/>; const news=x.data?.news??[]; return <FlatList style={st.page} data={news} keyExtractor={(_,i)=>String(i)} refreshControl={<RefreshControl refreshing={x.refreshing} onRefresh={x.refresh} tintColor={C.yellow}/>} ListHeaderComponent={<ScreenTitle kicker="MONDO SGM" title="News"/>} ListEmptyComponent={<Empty text="Nessuna news pubblicata."/>} renderItem={({item:n})=><Card>{n.image?<Image source={{uri:n.image}} style={st.newsImg}/>:null}<Text style={st.newsTitle}>{n.title}</Text><Text style={st.muted}>{n.date}</Text><Text style={st.body}>{n.body??n.excerpt}</Text></Card>}/>}

function Risultati(){const x=useSite(); if(x.loading&&!x.data)return <Loader/>; const d=x.data??{}; return <ScrollView style={st.page} refreshControl={<RefreshControl refreshing={x.refreshing} onRefresh={x.refresh} tintColor={C.yellow}/>}><ScreenTitle kicker="STAGIONE SPORTIVA" title="Risultati e classifiche"/><ScreenTitle title="Ultimi risultati"/><>{(d.recent_results??[]).map((m,i)=><Card key={i}><Text style={st.yellow}>{m.sport}</Text><View style={st.scoreRow}><Text style={st.team}>{m.home}</Text><Text style={st.score}>{m.home_score} - {m.away_score}</Text><Text style={[st.team,{textAlign:'right'}]}>{m.away}</Text></View><Text style={st.muted}>{m.date}</Text></Card>)}</><ScreenTitle title="Classifiche"/><>{sportsOrder.map(k=>{const s=d.sports?.[k]; if(!s?.standings?.length)return null; return <Card key={k}><Text style={st.sportTitle}>{s.name}</Text><Text style={st.yellow}>{s.league_name}</Text>{s.standings.map((r,i)=><View key={i} style={st.tableRow}><Text style={st.pos}>{r.pos||i+1}</Text><Text style={st.tableTeam}>{r.team}</Text><Text style={st.pts}>{r.points??0} pt</Text></View>)}</Card>})}</></ScrollView>}

function Altro(){const x=useSite(); if(x.loading&&!x.data)return <Loader/>; const d=x.data??{}; return <ScrollView style={st.page} refreshControl={<RefreshControl refreshing={x.refreshing} onRefresh={x.refresh} tintColor={C.yellow}/>}><ScreenTitle kicker="ASD SGM" title="Altro"/><Card><Text style={st.sportTitle}>Palmarès</Text><Text style={st.muted}>{Array.isArray(d.palmares)?`${d.palmares.length} elementi disponibili`:'Sezione disponibile dal sito'}</Text></Card><Card><Text style={st.sportTitle}>SGM TV</Text><Text style={st.muted}>{Array.isArray(d.sgm_tv)?`${d.sgm_tv.length} contenuti disponibili`:'Sezione disponibile dal sito'}</Text></Card><Card><Text style={st.sportTitle}>Sponsor</Text><Text style={st.muted}>{Array.isArray(d.sponsors)?`${d.sponsors.length} sponsor/contenuti disponibili`:'Sezione disponibile dal sito'}</Text></Card><Card><Text style={st.sportTitle}>Sincronizzazione</Text><Text style={st.body}>L’app legge lo stesso record Supabase usato dal sito. Quando salvi dal pannello amministratore, i nuovi dati vengono riletti automaticamente anche qui.</Text></Card></ScrollView>}

export default function App(){
 useEffect(()=>{registerForPushNotificationsAsync().catch(()=>null);},[]);
 return <NavigationContainer><StatusBar style="light"/><Tab.Navigator screenOptions={({route})=>({headerStyle:{backgroundColor:C.black},headerTintColor:C.white,headerTitleStyle:{fontWeight:'900'},tabBarStyle:{backgroundColor:C.black,borderTopColor:C.border,height:68,paddingBottom:8},tabBarActiveTintColor:C.yellow,tabBarInactiveTintColor:C.gray,tabBarLabelStyle:{fontWeight:'800'},tabBarIcon:({color})=><Text style={{color,fontSize:19}}>{icons[route.name]??'•'}</Text>})}><Tab.Screen name="Home" component={Home}/><Tab.Screen name="Squadre" component={Squadre}/><Tab.Screen name="News" component={News}/><Tab.Screen name="Risultati" component={Risultati}/><Tab.Screen name="Altro" component={Altro}/></Tab.Navigator></NavigationContainer>
}

const st=StyleSheet.create({page:{flex:1,backgroundColor:C.black},center:{flex:1,backgroundColor:C.black,alignItems:'center',justifyContent:'center',gap:12},muted:{color:C.gray,fontSize:13,lineHeight:18},yellow:{color:C.yellow,fontSize:12,fontWeight:'900',letterSpacing:.5},match:{color:C.white,fontSize:17,fontWeight:'800',marginVertical:8},newsImg:{width:'100%',height:190,borderRadius:12,marginBottom:12,backgroundColor:C.border},newsTitle:{color:C.white,fontSize:20,fontWeight:'900',marginBottom:4},body:{color:C.white,fontSize:14,lineHeight:21,marginTop:8},sportTitle:{color:C.white,fontSize:23,fontWeight:'900',marginBottom:5},sectionLabel:{color:C.yellow,fontWeight:'900',fontSize:11,letterSpacing:1.2,marginTop:18,marginBottom:8},row:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:9,borderBottomWidth:1,borderBottomColor:C.border},number:{color:C.yellow,fontSize:20,fontWeight:'900',width:34},rowTitle:{color:C.white,fontWeight:'800',fontSize:15},staffRow:{paddingVertical:8,borderBottomWidth:1,borderBottomColor:C.border},scoreRow:{flexDirection:'row',alignItems:'center',marginVertical:10},team:{color:C.white,fontSize:13,fontWeight:'800',flex:1},score:{color:C.yellow,fontSize:24,fontWeight:'900',paddingHorizontal:10},tableRow:{flexDirection:'row',alignItems:'center',paddingVertical:10,borderBottomWidth:1,borderBottomColor:C.border},pos:{color:C.yellow,fontWeight:'900',width:28},tableTeam:{color:C.white,fontWeight:'700',flex:1},pts:{color:C.white,fontWeight:'900'}});
